### ISSUE TITLE
Missing `trace` and `conf_pfabric_perfect.txt"?

### ISSUE THREAD

**Issue by shuwens** [vojislavdjukic/flux#1]
Hi Vojislav, 

I just get back from NSDI and was playing with the simulator. However, when I execute the `run_all.py` script I got the following errors. I guess I must have missed some important steps?

```
cd /home/jethros/dev/flux/simulator/py/tensorflow && python run_experiments.py
Traceback (most recent call last):
  File "generate_config.py", line 29, in <module>
    with open(confFile, 'w') as f:
IOError: [Errno 2] No such file or directory: './input/conf_pfabric_perfect.txt'
Traceback (most recent call last):
  File "run_experiments.py", line 30, in <module>
    map( os.unlink, (os.path.join('trace',f) for f in os.listdir('trace')) )
OSError: [Errno 2] No such file or directory: 'trace'
```

Also, executing the `simulator` binary gives me a segfault. Do you have any idea what happened? Thx

**Comment by shuwens** [comment]
Ok, I figured out the missing folder part--I should create them manually.
